/* Gui Texts */

/* Window */
TWIN_TITLE          Продукты
TWIN_FIRST          Первая запись
TWIN_BACK           Предыдущая запись
TWIN_NEXT           Следующая запись
TWIN_LAST           Последняя запись
TWIN_ADD            Добавить новую запись
TWIN_DEL            Удалить текущую запись
TWIN_FILTER_DESC    Поиск продуктов по описанию
TWIN_FILTER         Поиск...
TWIN_SETTINGS_PANEL Показать/Скрыть панель входа
TWIN_CODE           Код
TWIN_TYPE_CODE      Код товара
TWIN_DESC           Описание
TWIN_TYPE_DESC      Описание продукта
TWIN_CPU            CPU
TWIN_GPU            GPU
TWIN_HDD            HDD
TWIN_SCD            SCD
TWIN_TYPE_PRICE     Цена продукта
TWIN_TYPE           Тип
TWIN_PRICE          Цена
TWIN_USER           Имя пользователя
TWIN_PASS           Пароль
TWIN_LOGIN_MSG      Пожалуйста, войдите на сервер, чтобы загрузить описания продуктов. Пользователи: Аманда, Бренда, Брайан, Джон. Пропуск: 1234
TWIN_LOGIN          Войти
TWIN_LOGOUT         Выйти
TWIN_SETLANG        Выберите язык

/* Status */
WAIT_LOGIN          Ожидание входа...
IN_LOGIN            Подключение к серверу...
OK_LOGIN            Данные были загружены правильно.
ERR_CONNECT         Ошибка подключения.
ERR_JSON            Ошибка в ответе JSON.
ERR_ACCESS          Неверный пользователь или пароль.

/* Menu */
TMEN_ABOUT          О продуктах
TMEN_PREFERS        Настройки ...
TMEN_QUIT           Выйти из продуктов
TMEN_IMPORT         Импортировать базу данных ...
TMEN_EXPORT         Экспорт базы данных ...
TMEN_EXIT           Выход
TMEN_LOGIN_PANEL    Панель входа
TMEN_LOGIN          Войти
TMEN_LOGOUT         Выйти
TMEN_FILE           Файл
TMEN_NAVIGATE       Навигация
TMEN_FIRST          Первый
TMEN_BACK           Назад
TMEN_NEXT           следующий
TMEN_LAST           Последний
TMEN_VIEW           Просмотр
TMEN_SERVER         Сервер
TMEN_HELP           Справка

/* Language */
LANGUAGE            язык
ENGLISH             English
SPANISH             Español
PORTUGUESE          Português
ITALIAN             Italiana
VIETNAMESE          Tiếng việt
RUSSIAN             русский
JAPANESE            日本語

