/* Gui Texts */

/* Window */
TWIN_TITLE          Productos
TWIN_FIRST          Primero
TWIN_BACK           Anterior
TWIN_NEXT           Siguiente
TWIN_LAST           Último
TWIN_ADD            Añadir nuevo
TWIN_DEL            Eliminar registro
TWIN_FILTER_DESC    Buscar productos por descripción.
TWIN_FILTER         Buscar...
TWIN_SETTINGS_PANEL Mostrar/Ocultar el panel de inicio de sesión
TWIN_CODE           Código
TWIN_TYPE_CODE      Código de producto
TWIN_DESC           Descripción
TWIN_TYPE_DESC      Descripción del producto
TWIN_CPU            CPU
TWIN_GPU            GPU
TWIN_HDD            HDD
TWIN_SCD            SCD
TWIN_TYPE_PRICE     Precio del producto
TWIN_TYPE           Tipo
TWIN_PRICE          Precio
TWIN_USER           Usuario
TWIN_PASS           Contraseña
TWIN_LOGIN_MSG      Por favor, inicie sesión para descargar productos. Usuarios: amanda, brenda, brian, john. Clave: 1234
TWIN_LOGIN          Inicio sesión
TWIN_LOGOUT         Cerrar sesión
TWIN_SETLANG        Selecionar idioma

/* Status */
WAIT_LOGIN          Esperando inicio de sesión...
IN_LOGIN            Conectando con el servidor...
OK_LOGIN            Los datos se han descargado correctamente.
ERR_CONNECT         Error de conexión.
ERR_JSON            Error en la respuesta JSON.
ERR_ACCESS          Usuario o contraseña inválidos.

/* Menu */
TMEN_ABOUT          Sobre Products
TMEN_PREFERS        Preferencias...
TMEN_QUIT           Cerrar Products
TMEN_IMPORT         Importar datos...
TMEN_EXPORT         Exportar datos...
TMEN_EXIT           Salir
TMEN_LOGIN_PANEL    Panel de sesión
TMEN_LOGIN          Iniciar sesión
TMEN_LOGOUT         Cerrar sesión
TMEN_FILE           Archivo
TMEN_NAVIGATE       Navegar
TMEN_FIRST          Primero
TMEN_BACK           Anterior
TMEN_NEXT           Siguiente
TMEN_LAST           Último
TMEN_VIEW           Vista
TMEN_SERVER         Servidor
TMEN_HELP           Ayuda

/* Language */
LANGUAGE            Idioma
ENGLISH             English
SPANISH             Español
PORTUGUESE          Português
ITALIAN             Italiana
VIETNAMESE          Tiếng việt
RUSSIAN             русский
JAPANESE            日本語

