/* Gui Texts */

/* Window */
TWIN_TITLE          Products
TWIN_FIRST          First record
TWIN_BACK           Previous record
TWIN_NEXT           Next record
TWIN_LAST           Last record
TWIN_ADD            Add a new record
TWIN_DEL            Delete the current record
TWIN_FILTER_DESC    Search products by description
TWIN_FILTER         Search...
TWIN_SETTINGS_PANEL Show/Hide the login panel
TWIN_CODE           Code
TWIN_TYPE_CODE      Product Code
TWIN_DESC           Description
TWIN_TYPE_DESC      Product Description
TWIN_CPU            CPU
TWIN_GPU            GPU
TWIN_HDD            HDD
TWIN_SCD            SCD
TWIN_TYPE_PRICE     Product Price
TWIN_TYPE           Type
TWIN_PRICE          Price
TWIN_USER           Username
TWIN_PASS           Password
TWIN_LOGIN_MSG      Please, login into the server to download product descriptions. Users: amanda, brenda, brian, john. Pass: 1234
TWIN_LOGIN          Login
TWIN_LOGOUT         Logout
TWIN_SETLANG        Select language

/* Status */
WAIT_LOGIN          Waiting for login...
IN_LOGIN            Connecting to server...
OK_LOGIN            Data has been downloaded correctly.
ERR_CONNECT         Connection error.
ERR_JSON            Error in JSON response.
ERR_ACCESS          Invalid user or password.

/* Menu */
TMEN_ABOUT          About Products
TMEN_PREFERS        Preferences...
TMEN_QUIT           Quit Products
TMEN_IMPORT         Import Database...
TMEN_EXPORT         Export Database...
TMEN_EXIT           Exit
TMEN_LOGIN_PANEL    Login panel
TMEN_LOGIN          Login
TMEN_LOGOUT         Log Out
TMEN_FILE           File
TMEN_NAVIGATE       Navigate
TMEN_FIRST          First
TMEN_BACK           Back
TMEN_NEXT           Next
TMEN_LAST           Last
TMEN_VIEW           View
TMEN_SERVER         Server
TMEN_HELP           Help

/* Language */
LANGUAGE            Language
ENGLISH             English
SPANISH             Español
PORTUGUESE          Português
ITALIAN             Italiana
VIETNAMESE          Tiếng việt
RUSSIAN             русский
JAPANESE            日本語
