/* Gui Texts */

/* Window */
TWIN_TITLE          Produtos
TWIN_FIRST          Primeiro
TWIN_BACK           Anterior
TWIN_NEXT           Próximo
TWIN_LAST           Last
TWIN_ADD            Adicionar novo
TWIN_DEL            Excluir registro
TWIN_FILTER_DESC    Pesquisar produtos por descrição.
TWIN_FILTER         Pesquisar...
TWIN_SETTINGS_PANEL Mostrar / ocultar o painel de login
TWIN_CODE           Código
TWIN_TYPE_CODE      Código do produto
TWIN_DESC           Descrição
TWIN_TYPE_DESC      Descrição do produto
TWIN_CPU            CPU
TWIN_GPU            GPU
TWIN_HDD            HDD
TWIN_SCD            SCD
TWIN_TYPE_PRICE     Preço do produto
TWIN_TYPE           Tipo
TWIN_PRICE          Preço
TWIN_USER           Usuário
TWIN_PASS           Senha
TWIN_LOGIN_MSG      Por favor, faça o login para baixar produtos. Usuários: amanda, brenda, brian, john. Código: 1234
TWIN_LOGIN          Login
TWIN_LOGOUT         Fechar sessão
TWIN_SETLANG        Selecione o idioma

/* Status */
WAIT_LOGIN          Aguardando o login...
IN_LOGIN            Conectando-se ao servidor...
OK_LOGIN            Os dados foram baixados corretamente.
ERR_CONNECT         Erro de conexão.
ERR_JSON            Erro na resposta JSON.
ERR_ACCESS          Usuário ou senha inválido.

/* Menu */
TMEN_ABOUT          Sobre Produtos
TMEN_PREFERS        Preferências...
TMEN_QUIT           Fechar Produtos
TMEN_IMPORT         Importar dados...
TMEN_EXPORT         Exportar dados...
TMEN_EXIT           Sair
TMEN_LOGIN_PANEL    Painel de login
TMEN_LOGIN          Login
TMEN_LOGOUT         Fechar sessão
TMEN_FILE           Arquivo
TMEN_NAVIGATE       Navegar
TMEN_FIRST          Primeiro
TMEN_BACK           Anterior
TMEN_NEXT           Próximo
TMEN_LAST           Último
TMEN_VIEW           Vista
TMEN_SERVER         Servidor
TMEN_HELP           Ajuda

/* Language */
LANGUAGE            Língua
ENGLISH             English
SPANISH             Español
PORTUGUESE          Português
ITALIAN             Italiana
VIETNAMESE          Tiếng việt
RUSSIAN             русский
JAPANESE            日本語
