/* Gui Texts */

/* Window */
TWIN_TITLE          Prodotti
TWIN_FIRST          Primo record
TWIN_BACK           Record precedente
TWIN_NEXT           Record successivo
TWIN_LAST           Ultimo record
TWIN_ADD            Aggiungi un nuovo record
TWIN_DEL            Elimina il record corrente
TWIN_FILTER_DESC    Cerca prodotti per descrizione
TWIN_FILTER         Cerca...
TWIN_SETTINGS_PANEL Mostra/nascondi il pannello di login
TWIN_CODE           Codice 
TWIN_TYPE_CODE      Codice prodotto
TWIN_DESC           Descrizione
TWIN_TYPE_DESC      Descrizione del prodotto
TWIN_CPU            CPU
TWIN_GPU            GPU
TWIN_HDD            HDD
TWIN_SCD            SCD
TWIN_TYPE_PRICE     Prezzo del prodotto
TWIN_TYPE           Tipo
TWIN_PRICE          Prezzo
TWIN_USER           Nome utente
TWIN_PASS           Password
TWIN_LOGIN_MSG      Per favore, accedi al server per scaricare le descrizioni dei prodotti. Utenti: amanda, brenda, brian, john. Passaggio: 1234
TWIN_LOGIN          Login
TWIN_LOGOUT         Esci
TWIN_SETLANG        Seleziona la lingua

/* Status */
WAIT_LOGIN          In attesa di accesso ...
IN_LOGIN            Connessione al server ...
OK_LOGIN            I dati sono stati scaricati correttamente.
ERR_CONNECT         Errore di connessione.
ERR_JSON            Errore nella risposta JSON.
ERR_ACCESS          Utente o password non validi.

/* Menu */
TMEN_ABOUT          Informazioni sui prodotti
TMEN_PREFERS        Preferenze...
TMEN_QUIT           Esci dai prodotti
TMEN_IMPORT         Importa database...
TMEN_EXPORT         Esporta database...
TMEN_EXIT           Uscita
TMEN_LOGIN_PANEL    Pannello di accesso
TMEN_LOGIN          Accesso
TMEN_LOGOUT         Esci
TMEN_FILE           File
TMEN_NAVIGATE       Naviga
TMEN_FIRST          Primo
TMEN_BACK           Indietro
TMEN_NEXT           Successivo
TMEN_LAST           Ultimo
TMEN_VIEW           Vista
TMEN_SERVER         Server
TMEN_HELP           Guida

/* Language */
LANGUAGE            Linguaggio
ENGLISH             English
SPANISH             Español
PORTUGUESE          Português
ITALIAN             Italiana
VIETNAMESE          Tiếng việt
RUSSIAN             русский
JAPANESE            日本語

