/* Gui Texts */

/* Window */
TWIN_TITLE          Sản phẩm
TWIN_FIRST          Bản ghi đầu tiên
TWIN_BACK           Bản ghi trước
TWIN_NEXT           Bản ghi tiếp theo
TWIN_LAST           Bản ghi cuối
TWIN_ADD            Thêm bản ghi mới
TWIN_DEL            Xóa bản ghi hiện tại
TWIN_FILTER_DESC    Tìm kiếm sản phẩm theo mô tả
TWIN_FILTER         Tìm kiếm...
TWIN_SETTINGS_PANEL Hiển thị/Ẩn bảng đăng nhập
TWIN_CODE           Mã
TWIN_TYPE_CODE      Mã sản phẩm
TWIN_DESC           Mô tả
TWIN_TYPE_DESC      Mô tả sản phẩm
TWIN_CPU            CPU
TWIN_GPU            GPU
TWIN_HDD            HDD
TWIN_SCD            SCD
TWIN_TYPE_PRICE     Giá sản phẩm
TWIN_TYPE           Loại
TWIN_PRICE          Giá
TWIN_USER           Tên người dùng
TWIN_PASS           Mật khẩu
TWIN_LOGIN_MSG      Vui lòng, đăng nhập vào máy chủ để tải xuống các mô tả sản phẩm. Người dùng: amanda, brenda, brian, john. Đạt: 1234
TWIN_LOGIN          Đăng nhập
TWIN_LOGOUT         Đăng xuất
TWIN_SETLANG        Chọn ngôn ngữ

/* Status */
WAIT_LOGIN          Đang chờ đăng nhập...
IN_LOGIN            Kết nối với máy chủ...
OK_LOGIN            Dữ liệu đã được tải xuống chính xác.
ERR_CONNECT         Lỗi kết nối.
ERR_JSON            Lỗi trong phản hồi JSON.
ERR_ACCESS          Người dùng hoặc mật khẩu không hợp lệ.

/* Menu */
TMEN_ABOUT          Giới thiệu về sản phẩm
TMEN_PREFERS        Tùy chọn...
TMEN_QUIT           Thoát khỏi sản phẩm
TMEN_IMPORT         Cơ sở dữ liệu nhập khẩu...
TMEN_EXPORT         Cơ sở dữ liệu xuất khẩu...
TMEN_EXIT           Thoát khỏi
TMEN_LOGIN_PANEL    Bảng đăng nhập
TMEN_LOGIN          Đăng nhập
TMEN_LOGOUT         Đăng xuất
TMEN_FILE           Tệp
TMEN_NAVIGATE       Điều hướng
TMEN_FIRST          Đầu tiên
TMEN_BACK           Quay lại
TMEN_NEXT           Tiếp theo
TMEN_LAST           Lần cuối
TMEN_VIEW           Xem
TMEN_SERVER         Máy chủ
TMEN_HELP           Trợ giúp

/* Language */
LANGUAGE            Ngôn ngữ
ENGLISH             English
SPANISH             Español
PORTUGUESE          Português
ITALIAN             Italiana
VIETNAMESE          Tiếng việt
RUSSIAN             русский
JAPANESE            日本語

