/* Gui Texts */

/* Window */
TWIN_TITLE          製品
TWIN_FIRST          最初のレコード
TWIN_BACK           前のレコード
TWIN_NEXT           次のレコード
TWIN_LAST           最後のレコード
TWIN_ADD            新しいレコードを追加する
TWIN_DEL            現在のレコードを削除
TWIN_FILTER_DESC    商品を説明で探す
TWIN_FILTER         検索...
TWIN_SETTINGS_PANEL ログインパネルを表示/隠す
TWIN_CODE           コード
TWIN_TYPE_CODE      製品コード
TWIN_DESC           の説明
TWIN_TYPE_DESC      製品の説明
TWIN_CPU            CPU
TWIN_GPU            GPU
TWIN_HDD            HDD
TWIN_SCD            SCD
TWIN_TYPE_PRICE     商品の価格
TWIN_TYPE           型
TWIN_PRICE          価格
TWIN_USER           ユーザー名
TWIN_PASS           パスワード
TWIN_LOGIN_MSG      サーバーに ログインして 製品の説明 をダウンロー ドしてく ださい。 ユーザー： アマ ンダ、 ブレ ンダ、 ブライアン、ジョン。 パス：1234
TWIN_LOGIN          ログイン
TWIN_LOGOUT         ログアウト
TWIN_SETLANG        言語を選択

/* Status */
WAIT_LOGIN          ログインを待っています...
IN_LOGIN            サーバーに接続しています...
OK_LOGIN            データは正しくダウンロードされました。
ERR_CONNECT         接続エラーです。
ERR_JSON JSON       応答でエラーが発生しました。
ERR_ACCESS          無効なユーザーまたはパスワードです。

/* Menu */
TMEN_ABOUT          製品について
TMEN_PREFERS        設定...
TMEN_QUIT           製品を終了する
TMEN_IMPORT         データベースのインポート...
TMEN_EXPORT         データベースのエクスポート...
TMEN_EXIT           出口
TMEN_LOGIN_PANEL    ログインパネル
TMEN_LOGIN          ログイン
TMEN_LOGOUT         ログアウト
TMEN_FILE           ファイル
TMEN_NAVIGATE       ナビゲート
TMEN_FIRST          ファースト
TMEN_BACK           戻る
TMEN_NEXT           次へ
TMEN_LAST           最後
TMEN_VIEW           ビュー
TMEN_SERVER         サーバ
TMEN_HELP           ヘルプ

/* Language */
LANGUAGE            言語
ENGLISH             English
SPANISH             Español
PORTUGUESE          Português
ITALIAN             Italiana
VIETNAMESE          Tiếng việt
RUSSIAN             русский
JAPANESE            日本語
